[package]
name = "atomicring"
version = "0.2.0"
authors = ["Crown Software GmbH"]
description = "AtomicRingBuffer is a lock free and highly concurrent ring buffer"
license = "MIT OR Apache-2.0"
repository = "https://github.com/eun-ice/atomicring"


